import { ASTEROID_CONFIG, BOUNDARY_CONFIG, PLANET_CONFIG, PLAYER_CONFIG, SCORE_REWARDS, SHIP_CONFIG, STATION_CONFIG, FPS, FRICTION, G_CONST, MAX_Z_DEPTH, MIN_DURATION_TAP_TO_MOVE, SCALE_IN_MOUSE_MODE, SCALE_IN_TOUCH_MODE, WORLD_BOUNDS, ZOOM_LEVELS, DOM } from './config.js';

export const State = {
    width: 0,
    height: 0,
    playerShip: null,
    worldOffsetX: 0,
    worldOffsetY: 0,
    velocity: { x: 0, y: 0 },
    roids: [],
    ships: [],
    playerShipBullets: [],
    enemyShipBullets: [],
    particles: [],
    shockwaves: [],
    ambientFogs: [],
    backgroundLayers: { nebulas: [], galaxies: [], starsNear: [], starsMid: [], starsFar: [] },
    playerReloadTime: 0,
    lastPlayerShotTime: 0,
    stationSpawnTimer: 0,
    level: 0,
    homePlanetId: null,
    homePlanetDestroyed: false,
    screenMessages: [],
    gameRunning: false,
    victoryState: false,
    loopStarted: false,
    inputMode: 'mouse',
    keys: { ArrowUp: false, ArrowDown: false, Space: false, ArrowLeft: false, ArrowRight: false, KeyA: false, KeyD: false, Shift: false },
    mouse: { x: 0, y: 0 },
    currentZoomIndex: 2,
    RADAR_RANGE: ZOOM_LEVELS ? ZOOM_LEVELS[2] : 3000,
    viewScale: 1.0,
    roidCounter: 0,
    pendingDebris: []
};
